**Задания из методички №3**

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    

а) данные матрицы нельзя перемножить, т.к. количество столбцов первой матрицы не равно количеству строк второй матрицы и количество столбцов второй матрицы не равно числ строк первой матрицы

б) В данном примере можно найти произведение A*B, т.к.количество столбцов матрицы А равно количеству строк матрицы В. Размерность матрицы А*В будет 2х3.

Матрицу В*А не получится,т.к. кол-во столбцов В не равно числу строк А. 

в) В данном случае можно умножать как А*В, так и В*А, т.к. в обоих случаем кол-во столбцов первой матрицы будет равно кол-ву строк второй.

В случае А*В размерность будет 8х8

В случае В*А размерность 3х3

г) В данном случае можно умножать как А*В, так и В*А. Размерности в обоих случаяхбудут 4х4.

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

Сумма будет равна
$\begin{pmatrix}
1+4 & -2+(-1)\\ 
3+0 & 0+5
\end{pmatrix}$<br>
ИТОГО
$\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$


Произведение равно: $\begin{pmatrix}
1*4+(-2)*0 & 1*(-1)+(-2)*5\\ 
3*4+0*0 & 3*(-1)+0*5
\end{pmatrix}$<br>
ИТОГО
$\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [ ]:
import numpy as np

A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'матрица А:\n{A}\n')
print(f'матрица B:\n{B}\n')

матрица А:
[[ 1 -2]
 [ 3  0]]

матрица B:
[[ 4 -1]
 [ 0  5]]



In [ ]:
print(f'сумма A+B:\n{A+B}\n')


print(f'произведение А*В: \n{A.dot(B)}\n')

сумма A+B:
[[ 5 -3]
 [ 3  5]]

произведение А*В: 
[[  4 -11]
 [ 12  -3]]



__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$\begin{pmatrix}
3*1 & 3*7\\ 
3*3 & 3*(-6)
\end{pmatrix} - \begin{pmatrix}
2*0 & 2*5\\ 
2*2 & 2*(-1)
\end{pmatrix}+\begin{pmatrix}
4*2 & 4*(-4)\\ 
4*1 & 4*1
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [ ]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
k=3


print(f'3A-2B+4C=\n{3*A - 2*B + 4*C}\n')

3A-2B+4C=
[[ 11  -5]
 [  9 -12]]



__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} * \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

In [ ]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'A*A.T=\n{A.dot(A.T)}\n')

A*A.T=
[[17 18 11]
 [18 29  4]
 [11  4 13]]



$ \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} * \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [ ]:
print(f'A.T*A=\n{A.T.dot(A)}\n')

A.T*A=
[[45  0]
 [ 0 14]]



__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

к сожалению, нет времени на выполнение этого задания

**Задания из методички №4**

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

а) $$sin^2x-(-cos^2x) = sin^2x+cos^2x = 1$$

б) т.к. матрица верхне-треугольная, ее определитель равен произведению элементов на главной диагонали: 4 * 5 * 9 = 180

вычтем из второй строки первую, умноженную на 4:<br>
$$\begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
7 & 8 & 9
\end{vmatrix}.$$

вычтем из третьей строки первую, умноженную на 7:<br>
$$\begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{vmatrix}.$$

вычтем из третьей строки вторую, умноженную на 2:<br>
$$\begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{vmatrix}.$$

т.к. есть нулевая строка, то определитель равен 0

Проверим расчеты в numpy

In [ ]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(A)

180.0

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(A)

0.0

In [ ]:
B=2*A
np.linalg.det(B)

1439.999999999999

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) согласно свойству $$det(AB)=detA\cdot detB.$$
Соответственно $det(A^{2}) = 4*4 = 16$

б) согласно свойству $$detA^{T}=detA.$$
Соответственно $$detA^{T}=4$$

б) согласно свойству $$detA^{T}=detA.$$
Соответственно $$detA^{T}=4$$

в) тут нужно еще знать размерность матрицы. В общем виде:
$det(2A)=4*2^n$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица вырожденная, если ее определитель равен 0. Найдем опеделитель матрицы. Прибавим к первой строке, умноженной на 2, вторую:
$$\begin{pmatrix}
0 & 0 & 0\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$

Имеем нулевую строку, значит определитель равен нулю и матрица вырожденная.

Можно было сразу об этом сказать, т.к. 1-я и вторая строки матрицы изначально линейно зависимы.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) вычтем из второй строки первую и из третьей первую, умноженную на 2:
$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
0 & -1 & -2
\end{pmatrix};$

вычтем из третьей строки вторую:
$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
0 & 0 & 0
\end{pmatrix};$

Третью строку можно удалить.
Ранг равен 2

б) вычтем из первой строки вторую и из третьей удвоенную вторую:
$\begin{pmatrix}
0 & 0 & 0 & -1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & -1\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Вычтем из певой строки третью:
$\begin{pmatrix}
0 & 0 & 0 & 0\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & -1\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Первую строку можно удалить:
$\begin{pmatrix}
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & -1\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Ранг матрицы равен 3 (можно выделить минор 3-го порядка с ненулевым определителем)

In [2]:
import numpy as np

A = np.array([[1, 2, 3], [1, 1, 1], [2,3,4]])
print(f'ранг матрицы из п.а): {np.linalg.matrix_rank(A)}')

ранг матрицы из п.а): 2


In [3]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'ранг матрицы из п.б): {np.linalg.matrix_rank(A)}')

ранг матрицы из п.б): 3
